"""Shared configuration for the similarity engine."""

from __future__ import annotations

DEFAULT_ARCHETYPE_PLAYER = "Kevin De Bruyne"
DEFAULT_TOP_N = 25
DEFAULT_FALLBACK_AGE = 27.0

FEATURE_COLUMNS = [
    "progressive_passes_p90",
    "key_passes_p90",
    "through_balls_p90",
    "pass_completion_pct",
    "passes_into_final_third_p90",
    "passes_into_penalty_area_p90",
    "crosses_p90",
    "switches_p90",
    "passes_attempted_p90",
    "passes_completed_p90",
    "avg_pass_length",
    "xa_p90",
    "shot_creating_actions_p90",
    "goal_creating_actions_p90",
    "chances_created_p90",
    "big_chances_created_p90",
    "progressive_carries_p90",
    "carries_into_final_third_p90",
    "carries_into_penalty_area_p90",
    "carries_p90",
    "carry_distance_p90",
    "goals_p90",
    "assists_p90",
    "shots_p90",
    "shots_on_target_p90",
    "xg_p90",
    "touches_p90",
    "ball_recoveries_p90",
    "turnovers_p90",
    "dispossessed_p90",
    "miscontrols_p90",
    "fouls_won_p90",
    "pressures_p90",
    "tackles_p90",
    "interceptions_p90",
    "duels_won_p90",
    "minutes_played",
    "starts",
    "matches_played",
    "age",
]

RADAR_FEATURE_COLUMNS = [
    "progressive_passes_p90",
    "key_passes_p90",
    "xa_p90",
    "goal_creating_actions_p90",
    "progressive_carries_p90",
    "passes_into_final_third_p90",
    "shots_p90",
    "pressures_p90",
]

FEATURE_LABELS = {
    "progressive_passes_p90": "Progressive Passes /90",
    "key_passes_p90": "Key Passes /90",
    "through_balls_p90": "Through Balls /90",
    "pass_completion_pct": "Pass Completion %",
    "passes_into_final_third_p90": "Final Third Passes /90",
    "passes_into_penalty_area_p90": "Penalty Area Passes /90",
    "crosses_p90": "Crosses /90",
    "switches_p90": "Switches /90",
    "passes_attempted_p90": "Passes Attempted /90",
    "passes_completed_p90": "Passes Completed /90",
    "avg_pass_length": "Average Pass Length",
    "xa_p90": "xA /90",
    "shot_creating_actions_p90": "Shot-Creating Actions /90",
    "goal_creating_actions_p90": "Goal-Creating Actions /90",
    "chances_created_p90": "Chances Created /90",
    "big_chances_created_p90": "Big Chances Created /90",
    "progressive_carries_p90": "Progressive Carries /90",
    "carries_into_final_third_p90": "Carries Into Final Third /90",
    "carries_into_penalty_area_p90": "Carries Into Penalty Area /90",
    "carries_p90": "Carries /90",
    "carry_distance_p90": "Carry Distance /90",
    "goals_p90": "Goals /90",
    "assists_p90": "Assists /90",
    "shots_p90": "Shots /90",
    "shots_on_target_p90": "Shots On Target /90",
    "xg_p90": "xG /90",
    "touches_p90": "Touches /90",
    "ball_recoveries_p90": "Ball Recoveries /90",
    "turnovers_p90": "Turnovers /90",
    "dispossessed_p90": "Dispossessed /90",
    "miscontrols_p90": "Miscontrols /90",
    "fouls_won_p90": "Fouls Won /90",
    "pressures_p90": "Pressures /90",
    "tackles_p90": "Tackles /90",
    "interceptions_p90": "Interceptions /90",
    "duels_won_p90": "Duels Won /90",
    "minutes_played": "Minutes Played",
    "starts": "Starts",
    "matches_played": "Matches Played",
    "age": "Age",
}
